inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable

Rails:
  Enabled: true

RSpec:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

Performance:
  Enabled: true

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - '**/*.gemspec'

Layout/IndentationConsistency:
  EnforcedStyle: normal

Style/BlockDelimiters:
  Enabled: true

Rails/ApplicationJob:
  Enabled: false

Rails/ApplicationMailer:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/otp/active_record.rb'

RSpec/DescribedClass:
  Enabled: false
